#!/bin/bash

VERSION=0.4.0-SNAPSHOT

exec "$(dirname "$0")/coursier" launch \
  com.github.alexarchambault:ammonite-shell_2.11.7:$VERSION \
  -I ammonium-compile:com.github.alexarchambault:ammonite-shell-api_2.11.7:$VERSION \
  -I ammonium-macro:org.scala-lang:scala-compiler:2.11.7 \
  -i ammonium-compile,ammonium-macro
