#!/bin/bash
set -ev

SCALA_VERSION="${TRAVIS_SCALA_VERSION:-2.10.5}"

# Spark 1.1 specific script

# Tests are run in a forked JVM
# On Travis, this leaves more memory to the forked JVM
export SBT_OPTS="-J-Xmx512m -J-Xms512m"
SBT="sbt ++$SCALA_VERSION"

for TEST in AdvancedTests AutocompleteTests EulerTests EvaluatorTests FailureTests SerializationTests; do
  $SBT "shell/test-only ammonite.shell.$TEST"
  $SBT "shell/test-only ammonite.shell.classwrapper.$TEST"
done

# Not running the spark tests on Travis for lack of memory
if [ "$TRAVIS_SCALA_VERSION" = "" ]; then
  $SBT "shell/test-only ammonite.shell.classwrapper.LocalSpark11Tests"
  $SBT "spark-11/test-only ammonite.spark.LocalTests"
fi
