#!/bin/bash
set -ev

export SBT_OPTS="-Xmx512M"
SBT="sbt ++${TRAVIS_SCALA_VERSION:-2.11.6}"

for TEST in AdvancedTests AutocompleteTests EulerTests EvaluatorTests FailureTests SerializationTests; do
  $SBT "shell/test-only ammonite.shell.$TEST"
  $SBT "shell/test-only ammonite.shell.classwrapper.$TEST"
done

$SBT "shell/test-only ammonite.shell.classwrapper.LocalSpark12Tests"
$SBT "shell/test-only ammonite.shell.classwrapper.LocalSpark13Tests"
$SBT "spark-12/test-only ammonite.spark.LocalTests"
$SBT "spark-13/test-only ammonite.spark.LocalTests"

if [ "$SPARK_HOME" != "" ]; then
  $SBT "spark-12/test-only ammonite.spark.LocalClusterTests"
  $SBT "spark-13/test-only ammonite.spark.LocalClusterTests"
  $SBT "spark-12/test-only ammonite.spark.StandAloneClusterTests"
  $SBT "spark-13/test-only ammonite.spark.StandAloneClusterTests"
fi

