#!/bin/bash
set -ev

PWD="$(cd "$(dirname "$0")"; pwd)"
SBT="sbt ++${TRAVIS_SCALA_VERSION:-2.11.8}"

$SBT publish-local | grep -v "exclude("

"$PWD/run-tests"

if [ "$TRAVIS_PULL_REQUEST" == "false" -a "$TRAVIS_BRANCH" == "master" ]; then
  $SBT publish
fi
