#!/bin/bash
set -ev

PWD="$(cd "$(dirname "$0")"; pwd)"

sbt ++2.10.5 "shell/test"
sbt "shell/test"
sbt ++2.10.5 "spark-12/test-only ammonite.spark.LocalTests"
sbt "spark-12/test-only ammonite.spark.LocalTests"
sbt ++2.10.5 "spark-13/test-only ammonite.spark.LocalTests"
sbt "spark-13/test-only ammonite.spark.LocalTests"

SPARK_HOME="/opt/spark-1.2_2.10" sbt ++2.10.5 "spark-12/test-only ammonite.spark.LocalClusterTests"
SPARK_HOME="/opt/spark-1.2_2.11" sbt "spark-12/test-only ammonite.spark.LocalClusterTests"
SPARK_HOME="/opt/spark-1.3_2.10" sbt ++2.10.5 "spark-13/test-only ammonite.spark.LocalClusterTests"
SPARK_HOME="/opt/spark-1.3_2.11" sbt "spark-13/test-only ammonite.spark.LocalClusterTests"

SPARK_VERSION="1.2" "$PWD/spark/src/test/resources/docker/scripts/run" . ++2.10.5 "spark-12/test-only ammonite.spark.StandAloneClusterTests"
SPARK_VERSION="1.3" "$PWD/spark/src/test/resources/docker/scripts/run" . ++2.10.5 "spark-13/test-only ammonite.spark.StandAloneClusterTests"
