#!/bin/bash
set -ev

# Spark 1.1 specific script

PWD="$(cd "$(dirname "$0")"; pwd)"
SBT="sbt ++${TRAVIS_SCALA_VERSION:-2.10.5}"

$SBT publish-local

"$PWD/run-tests"

if [ "$TRAVIS_PULL_REQUEST" == "false" -a "$JAVA_HOME" == "$1" -a "$TRAVIS_BRANCH" == "topic/spark-1.1" ]; then
  $SBT spark-11/publish
fi
