#!/bin/bash
set -ev

# Spark 1.1 specific script

PWD="$(cd "$(dirname "$0")"; pwd)"

sbt ++2.10.5 "spark-11/test-only ammonite.spark.LocalTests"

SPARK_HOME="/opt/spark-1.1_2.10" sbt ++2.10.5 "spark-11/test-only ammonite.spark.LocalClusterTests"

SPARK_VERSION="1.1" "$PWD/spark/src/test/resources/docker/scripts/run" . ++2.10.5 "spark-11/test-only ammonite.spark.StandAloneClusterTests"
