#!/bin/bash
set -ev

SCALA_VERSION="${TRAVIS_SCALA_VERSION:-2.11.7}"

# Tests are run in a forked JVM
# On Travis, this leaves more memory to the forked JVM
export SBT_OPTS="-J-Xmx512m -J-Xms512m"
SBT="sbt ++$SCALA_VERSION"

for TEST in AdvancedTests AutocompleteTests EulerTests EvaluatorTests FailureTests SerializationTests; do
  $SBT "shell/test-only ammonite.shell.$TEST"
  $SBT "shell/test-only ammonite.shell.classwrapper.$TEST"
done

# Not running the spark tests on Travis for lack of memory
if [ "$TRAVIS_SCALA_VERSION" = "" ]; then
  $SBT "shell/test-only ammonite.shell.classwrapper.LocalSpark12Tests"
  $SBT "shell/test-only ammonite.shell.classwrapper.LocalSpark13Tests"
  $SBT "shell/test-only ammonite.shell.classwrapper.LocalSpark14Tests"
  $SBT "shell/test-only ammonite.shell.classwrapper.LocalSpark15Tests"
  $SBT "spark-12/test-only ammonite.spark.LocalTests"
  $SBT "spark-13/test-only ammonite.spark.LocalTests"
  $SBT "spark-14/test-only ammonite.spark.LocalTests"
  $SBT "spark-15/test-only ammonite.spark.LocalTests"
fi
