#!/bin/bash

if [ "$SPARK_VERSION" = "" ]; then
  echo "SPARK_VERSION not set" 1>&2
  exit 255
fi

for i in $(seq 1 3); do
  docker exec -it "slave${i}-$SPARK_VERSION" /bin/bash -c "rm -rf /opt/spark-1.?/work"
  docker exec -it "slave${i}-$SPARK_VERSION" /bin/bash -c "rm -rf /tmp/spark-*"
done
