#!/bin/bash
set -e

docker ps | grep -q "\<master\>" || docker run -d -p 8080 -h master --name master test_spark/master
sleep 5

for i in $(seq 1 3); do
  docker ps | grep -q "\<slave$i\>" || docker run -d -p 8080 -h "slave$i" --name "slave$i" --link master:master test_spark/slave
done

exec docker run -it --rm -h "sbt" --name "sbt" --link master:master $(for i in $(seq 1 3); do echo " --link slave$i:slave$i"; done) -v "$(cd "$(dirname "$0")/../../../../../.."; pwd):/ammonite-shell" "$@" test_spark/sbt
